package com.example.weatherMonitoringApp.user;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping("/")// This means URL's start with '/' (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         	 // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestParam String first_name
		  								, @RequestParam String last_name
		  								, @RequestParam String username
		  								, @RequestParam String email
		  								, @RequestParam String password
		  								, @RequestParam String home_place
		  								, @RequestParam String favourite_place) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setFirst_name(first_name);
    n.setLast_name(last_name);
    n.setUsername(username);
    n.setEmail(email);
    n.setPassword(password);
    n.setHome_place(home_place);
    n.setFavourite_place(favourite_place);
    userRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/allUsers")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }

}